# Set vi keys
set-window-option -g mode-keys vi
set-option -g status-keys vi

# Set 256 color
set-option -sa terminal-features ',xterm-256color:RGB'

# Start windows at 1 instead of 0
set -g base-index 1

# Start panes at 1 instead of 0
setw -g pane-base-index 1

# Renumber windows automatically when one is closed
set-option -g renumber-windows on

# Enable setting the system clipboard
# 'on' allows applications inside tmux to set tmux's buffer AND system clipboard
# 'external' only allows tmux itself to set system clipboard
set -g set-clipboard on

# Ensure that the terminal-features capability is correctly set for OSC 52.
# This is for tmux 3.2a and later.
# Replace 'xterm-256color' with your actual $TERM outside tmux if different.
set-option -sa terminal-features ',xterm-256color:clipboard'


set -g history-limit 10000 # Set to 10,000 lines, or your desired value

# Some KEYBINDS!

# Reload key bind
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Tmux config reloaded!"

bind C-s setw synchronize-panes \; display-message "Synchronize panes #{?pane_synchronized,ON,OFF}"
